[[countries]]
name="Belgium"
code="BE"

[ecli]
    [ecli.BE]
        [ecli.BE.GHCC]
            code = "GHCC"
            name = "Constitutional Court"
        [ecli.BE.RVSCDE]
            code = "RVSCDE"
            name = "Council of State"
            def_file = "RVSCDE_def.json"
